# Generated by Django 2.2.1 on 2019-05-26 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturl',
            name='count',
            field=models.BigIntegerField(default=0),
        ),
    ]
